export const NEW_INGREDIENT: 'NEW_INGREDIENT' = 'NEW_INGREDIENT'
export const CONSTRUCTOR_ADD: 'CONSTRUCTOR_ADD' = 'CONSTRUCTOR_ADD';
export const CONSTRUCTOR_DELETE: 'CONSTRUCTOR_DELETE' = 'CONSTRUCTOR_DELETE';
export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR_REORDER' = 'CONSTRUCTOR_REORDER';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET' = 'CONSTRUCTOR_RESET';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const SET_USER_AUTH: 'SET_USER_AUTH' = "SET_USER_AUTH";
export const SET_USER: 'SET_USER' = "SET_USER";
export const CLEAR_USER: 'CLEAR_USER' = "CLEAR_USER";

export const SET_INGREDIENT_MODAL: 'SET_INGREDIENT_MODAL' = 'SET_INGREDIENT_MODAL';
export const RESET_INGREDIENT_MODAL: 'RESET_INGREDIENT_MODAL' = 'RESET_INGREDIENT_MODAL';

export const SET_LOADING: 'SET_LOADING' = 'SET_LOADING';